### ISSUE TITLE
Hotkeys aren't working

### ISSUE THREAD

**Issue by jayandare** [thx114/mio-hotkey-mod#1]
My output log says it's loaded but none of the buttons or shortcuts are working. Even double click left mouse doesn't work. I've been waiting for a hockey mod like this to make its way over from the first city skylines, I have some trouble with my hands and it makes it so much more enjoyable playing a game with a mod like this. Is there anything I can do to help get this working?

**Comment by thx114** [comment]
This mod depends on HookUI 0.3.5.
Please make sure you are using the latest version of HookUI.

Currently, double-clicking the left mouse button can only close a few menus. If you have urgent ideas or suggestions, please let me know.
